# Generated by Django 2.1.5 on 2020-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
