# Generated by Django 2.1.5 on 2020-01-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_auto_20200122_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
