# Generated by Django 2.1.5 on 2020-01-22 17:41

import courier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0010_auto_20200122_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='status',
            field=models.CharField(choices=[(courier.models.OrderStatus(('Placed Order',)), 'Placed'), (courier.models.OrderStatus(('Confirmed Order',)), 'Confirmed'), (courier.models.OrderStatus(('Confirmed Order',)), 'Confirmed'), (courier.models.OrderStatus(('Dispatched Product',)), 'Dispatched'), (courier.models.OrderStatus(('Reached Product',)), 'Reached'), (courier.models.OrderStatus('Delivered Product'), 'Delivered')], default=courier.models.OrderStatus(('Placed Order',)), max_length=50),
        ),
    ]
