# Generated by Django 2.1.5 on 2020-01-22 17:46

import courier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0011_auto_20200122_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='status',
            field=models.CharField(choices=[(courier.models.OrderStatus(('Placed Order',)), 'Placed Order'), (courier.models.OrderStatus(('Confirmed Order',)), 'Confirmed Order'), (courier.models.OrderStatus(('Picked-up',)), 'Picked-up'), (courier.models.OrderStatus(('Dispatched Product',)), 'Dispatched Product'), (courier.models.OrderStatus(('Reached Product',)), 'Reached Product'), (courier.models.OrderStatus('Delivered Product'), 'Delivered Product')], default=courier.models.OrderStatus(('Placed Order',)), max_length=50),
        ),
    ]
