# Generated by Django 2.1.5 on 2020-01-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0013_auto_20200123_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='status',
            field=models.CharField(choices=[('Placed Order', 'Placed Order'), ('Confirmed Order', 'Confirmed Order'), ('Picked-up', 'Picked-up'), ('Dispatched Product', 'Dispatched Product'), ('Reached Product', 'Reached Product'), ('Delivered Product', 'Delivered Product')], default='Placed Order', max_length=50),
        ),
    ]
