# Generated by Django 2.1.5 on 2020-01-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0015_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
