# Generated by Django 2.1.5 on 2020-01-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0016_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=300)),
                ('email', models.EmailField(default='', max_length=111)),
                ('phone', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_email',
            field=models.EmailField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_email',
            field=models.EmailField(default='', max_length=111),
        ),
    ]
