# Generated by Django 2.1.5 on 2020-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0019_auto_20200130_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
