# Generated by Django 2.1.5 on 2020-01-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0020_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_order',
            fields=[
                ('pending_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
